// Curated set of note icons from lucide-react (used by the "Set icon" picker).
// Icons are stored on a note by their string NAME (e.g. "Star"), never as an emoji.
import {
  FileText,
  StickyNote,
  BookOpen,
  Notebook,
  NotebookPen,
  ScrollText,
  Star,
  Sparkles,
  Flame,
  Lightbulb,
  Target,
  Flag,
  Pin,
  Bookmark,
  Tag,
  Link,
  CheckCircle,
  ListChecks,
  AlertTriangle,
  HelpCircle,
  MessageSquare,
  Quote,
  Bell,
  Clock,
  Calendar,
  BarChart3,
  TrendingUp,
  LineChart,
  PieChart,
  Calculator,
  Ruler,
  Hash,
  Brain,
  Microscope,
  FlaskConical,
  Telescope,
  Dna,
  Sprout,
  Leaf,
  Rocket,
  Wrench,
  Settings,
  Puzzle,
  Palette,
  Brush,
  Pencil,
  PenTool,
  Map,
  MapPin,
  Compass,
  Music,
  Film,
  Camera,
  Gamepad2,
  Trophy,
  GraduationCap,
  Briefcase,
  Home,
  Globe,
  Moon,
  Sun,
  Heart,
  Zap,
  Coffee,
  Code,
  Terminal,
  Database,
  Folder,
  Image,
  Bug,
  Shield,
  Key,
  Lock,
  Mail,
  User,
  Users,
  Cloud,
  Feather,
  Anchor,
  Award,
  Beaker,
  DollarSign,
  Gift,
  Landmark,
  Layers,
  Package,
  Paperclip,
  Scale,
  ShoppingCart,
  Table,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const NOTE_ICONS: Record<string, LucideIcon> = {
  FileText, StickyNote, BookOpen, Notebook, NotebookPen, ScrollText,
  Star, Sparkles, Flame, Lightbulb, Target, Flag, Pin, Bookmark, Tag, Link,
  CheckCircle, ListChecks, AlertTriangle, HelpCircle, MessageSquare, Quote, Bell, Clock, Calendar,
  BarChart3, TrendingUp, LineChart, PieChart, Calculator, Ruler, Hash,
  Brain, Microscope, FlaskConical, Telescope, Dna, Sprout, Leaf,
  Rocket, Wrench, Settings, Puzzle, Palette, Brush, Pencil, PenTool, Map, MapPin, Compass,
  Music, Film, Camera, Gamepad2, Trophy, GraduationCap, Briefcase, Home, Globe, Moon, Sun, Heart, Zap, Coffee,
  Code, Terminal, Database, Folder, Image, Bug, Shield, Key, Lock, Mail, User, Users, Cloud, Feather,
  Anchor, Award, Beaker, DollarSign, Gift, Landmark, Layers, Package, Paperclip, Scale, ShoppingCart, Table, Wallet,
};

export const NOTE_ICON_NAMES = Object.keys(NOTE_ICONS);

/** Render a note's icon by name. Falls back to raw text (backward compat with any old emoji icons). */
export function NoteIcon({ name, size = 15, className }: { name: string; size?: number; className?: string }) {
  const Ico = NOTE_ICONS[name];
  if (Ico) return <Ico size={size} className={className} strokeWidth={1.9} />;
  return <span className={className}>{name}</span>;
}
